import '../data/models/protocol.dart';
import '../data/models/protocol_step.dart';

class DefaultTemplates {
  static List<ProtocolTemplate> get pack => [
        ProtocolTemplate(
          id: 'emergency_evacuation',
          nameEn: 'Emergency Evacuation (Universal)',
          nameTr: 'Acil Tahliye (Evrensel)',
          descriptionEn: 'When negotiation starts, we evacuate. One job: outlast the wave.',
          descriptionTr: 'Pazarlık başladıysa tahliye. Tek iş: dalgayı atlatmak.',
          steps: [
            ProtocolStep(
              id: 'evac_step_1',
              titleEn: 'No negotiation — press start now.',
              titleTr: 'Pazarlık yok — şimdi başlat.',
              type: ProtocolStepType.action,
              critical: true,
              order: 0,
            ),
            ProtocolStep(
              id: 'evac_step_2',
              titleEn: 'Lock device / put phone away.',
              titleTr: 'Cihazı kilitle / telefonu kaldır.',
              type: ProtocolStepType.checkbox,
              critical: true,
              order: 1,
            ),
            ProtocolStep(
              id: 'evac_step_3',
              titleEn: 'Exit the room immediately. Shoes on.',
              titleTr: 'Hemen odadan çık. Ayakkabını giy.',
              type: ProtocolStepType.action,
              critical: true,
              order: 2,
            ),
            ProtocolStep(
              id: 'evac_step_4',
              titleEn: 'Walk 30 minutes.',
              titleTr: '30 dk yürüyüş.',
              type: ProtocolStepType.timer,
              durationSec: 1800,
              critical: true,
              order: 3,
            ),
            ProtocolStep(
              id: 'evac_step_5',
              titleEn: 'Water + 10 slow breaths.',
              titleTr: 'Su + 10 yavaş nefes.',
              type: ProtocolStepType.timer,
              durationSec: 120,
              order: 4,
            ),
            ProtocolStep(
              id: 'evac_step_6',
              titleEn: 'Return home: internet OFF for 60 minutes.',
              titleTr: 'Eve dön: internet 60 dk kapalı.',
              type: ProtocolStepType.timer,
              durationSec: 3600,
              critical: true,
              order: 5,
            ),
            ProtocolStep(
              id: 'evac_step_7',
              titleEn: 'Mark: “I survived this wave.”',
              titleTr: 'İşaretle: “Bu dalgayı atlattım.”',
              type: ProtocolStepType.checkbox,
              order: 6,
            ),
          ],
          recommendedFor: const ['lust', 'nicotine', 'scrolling', 'gambling', 'sugar', 'gaming', 'shopping', 'custom'],
        ),
        ProtocolTemplate(
          id: 'warning_interrupt',
          nameEn: 'Warning — Interrupt Loop (90s)',
          nameTr: 'Uyarı — Döngüyü Kır (90 sn)',
          descriptionEn: "You’re about to negotiate. Break the loop fast.",
          descriptionTr: 'Pazarlık başlıyor. Döngüyü hızlı kır.',
          steps: [
            ProtocolStep(
              id: 'warn_step_1',
              titleEn: 'Stand up NOW.',
              titleTr: 'Hemen ayağa kalk.',
              type: ProtocolStepType.action,
              critical: true,
              order: 0,
            ),
            ProtocolStep(
              id: 'warn_step_2',
              titleEn: 'Phone away / screen down.',
              titleTr: 'Telefonu kaldır / ekranı ters çevir.',
              type: ProtocolStepType.checkbox,
              critical: true,
              order: 1,
            ),
            ProtocolStep(
              id: 'warn_step_3',
              titleEn: 'Cold water on face or hands.',
              titleTr: 'Yüze veya ellere soğuk su.',
              type: ProtocolStepType.action,
              order: 2,
            ),
            ProtocolStep(
              id: 'warn_step_4',
              titleEn: '90 seconds breathe: inhale 4, hold 2, exhale 6.',
              titleTr: '90 sn nefes: 4 al, 2 tut, 6 ver.',
              type: ProtocolStepType.breathing,
              durationSec: 90,
              critical: true,
              order: 3,
            ),
            ProtocolStep(
              id: 'warn_step_5',
              titleEn: 'Choose next: Evacuate (30m) OR Safe task (5m).',
              titleTr: 'Seç: Tahliye (30dk) veya Güvenli görev (5dk).',
              type: ProtocolStepType.checkbox,
              order: 4,
            ),
          ],
          recommendedFor: const ['scrolling', 'lust', 'gaming', 'shopping', 'nicotine', 'gambling', 'custom'],
        ),
        ProtocolTemplate(
          id: 'digital_lockdown',
          nameEn: 'Digital Lockdown (Access Removal)',
          nameTr: 'Dijital Karantina (Erişimi Kes)',
          descriptionEn: 'Make the “easy reward” path expensive.',
          descriptionTr: '“Kolay ödül” yolunu pahalılaştır.',
          steps: [
            ProtocolStep(
              id: 'lock_step_1',
              titleEn: 'Put phone in lockbox / out of reach.',
              titleTr: 'Telefonu kutuya koy / erişimi kes.',
              type: ProtocolStepType.checkbox,
              critical: true,
              order: 0,
            ),
            ProtocolStep(
              id: 'lock_step_2',
              titleEn: 'Disconnect internet (Wi-Fi off / unplug).',
              titleTr: 'İnterneti kapat (Wi-Fi kapat / fişi çek).',
              type: ProtocolStepType.action,
              critical: true,
              order: 1,
            ),
            ProtocolStep(
              id: 'lock_step_3',
              titleEn: 'Leave the room for 10 minutes.',
              titleTr: '10 dk odadan çık.',
              type: ProtocolStepType.timer,
              durationSec: 600,
              critical: true,
              order: 2,
            ),
            ProtocolStep(
              id: 'lock_step_4',
              titleEn: 'Do a physical reset: stretch / push-ups / quick tidy.',
              titleTr: 'Fiziksel reset: esneme / şınav / toparlama.',
              type: ProtocolStepType.timer,
              durationSec: 300,
              order: 3,
            ),
            ProtocolStep(
              id: 'lock_step_5',
              titleEn: 'Re-enter with a plan: only 1 allowed task.',
              titleTr: 'Planla geri dön: sadece 1 izinli iş.',
              type: ProtocolStepType.checkbox,
              order: 4,
            ),
          ],
          recommendedFor: const ['scrolling', 'gaming', 'shopping', 'gambling'],
        ),
        ProtocolTemplate(
          id: 'nicotine_shield',
          nameEn: 'Nicotine Craving — 10 Minute Shield',
          nameTr: 'Nikotin Krizi — 10 Dakika Kalkan',
          descriptionEn: 'Craving peaks fast; ride it out.',
          descriptionTr: 'İstek hızlı yükselir; dalgayı atlat.',
          steps: [
            ProtocolStep(
              id: 'nico_step_1',
              titleEn: 'Drink water now.',
              titleTr: 'Şimdi su iç.',
              type: ProtocolStepType.checkbox,
              critical: true,
              order: 0,
            ),
            ProtocolStep(
              id: 'nico_step_2',
              titleEn: '2 minutes deep breathing.',
              titleTr: '2 dk derin nefes.',
              type: ProtocolStepType.timer,
              durationSec: 120,
              critical: true,
              order: 1,
            ),
            ProtocolStep(
              id: 'nico_step_3',
              titleEn: '5 minutes walk or stairs.',
              titleTr: '5 dk yürüyüş veya merdiven.',
              type: ProtocolStepType.timer,
              durationSec: 300,
              critical: true,
              order: 2,
            ),
            ProtocolStep(
              id: 'nico_step_4',
              titleEn: 'Text replacement: gum / tea / shower / brush teeth.',
              titleTr: 'Yerine koy: sakız / çay / duş / diş fırçala.',
              type: ProtocolStepType.checkbox,
              order: 3,
            ),
            ProtocolStep(
              id: 'nico_step_5',
              titleEn: 'Mark: “Not today.”',
              titleTr: 'İşaretle: “Bugün değil.”',
              type: ProtocolStepType.checkbox,
              order: 4,
            ),
          ],
          recommendedFor: const ['nicotine'],
        ),
        ProtocolTemplate(
          id: 'food_delay_replace',
          nameEn: 'Food Urge — Delay & Replace (12 min)',
          nameTr: 'Yeme İsteği — Ertele & Değiştir (12 dk)',
          descriptionEn: 'Delay reduces compulsion; replace with body regulation.',
          descriptionTr: 'Erteleme kompulsiyonu kırar; beden regülasyonu ekle.',
          steps: [
            ProtocolStep(
              id: 'food_step_1',
              titleEn: 'Drink water + pinch of salt (optional).',
              titleTr: 'Su iç (istersen az tuz).',
              type: ProtocolStepType.checkbox,
              order: 0,
            ),
            ProtocolStep(
              id: 'food_step_2',
              titleEn: 'Wait 8 minutes (no kitchen).',
              titleTr: '8 dk bekle (mutfağa girme).',
              type: ProtocolStepType.timer,
              durationSec: 480,
              critical: true,
              order: 1,
            ),
            ProtocolStep(
              id: 'food_step_3',
              titleEn: 'Brush teeth OR mint gum.',
              titleTr: 'Diş fırçala veya naneli sakız.',
              type: ProtocolStepType.checkbox,
              critical: true,
              order: 2,
            ),
            ProtocolStep(
              id: 'food_step_4',
              titleEn: 'If still hungry: eat a planned snack.',
              titleTr: 'Hâlâ açsan: planlı atıştırmalık.',
              type: ProtocolStepType.checkbox,
              order: 3,
            ),
          ],
          recommendedFor: const ['sugar', 'custom'],
        ),
        ProtocolTemplate(
          id: 'spiritual_reset',
          nameEn: 'Spiritual Reset (Optional)',
          nameTr: 'Manevi Reset (Opsiyonel)',
          descriptionEn: 'Calm the system and return to intention.',
          descriptionTr: 'Sistemi sakinleştir, niyete dön.',
          steps: [
            ProtocolStep(
              id: 'spirit_step_1',
              titleEn: 'Wash / wudu or face rinse.',
              titleTr: 'Abdest / yüz yıkama.',
              type: ProtocolStepType.checkbox,
              critical: true,
              order: 0,
            ),
            ProtocolStep(
              id: 'spirit_step_2',
              titleEn: '2 minutes breathing.',
              titleTr: '2 dk nefes.',
              type: ProtocolStepType.timer,
              durationSec: 120,
              order: 1,
            ),
            ProtocolStep(
              id: 'spirit_step_3',
              titleEn: '2 minutes quiet prayer / reflection.',
              titleTr: '2 dk dua / tefekkür.',
              type: ProtocolStepType.timer,
              durationSec: 120,
              critical: true,
              order: 2,
            ),
            ProtocolStep(
              id: 'spirit_step_4',
              titleEn: 'Read 1 page / 5 verses / or a short reminder.',
              titleTr: '1 sayfa / birkaç ayet / kısa hatırlatma.',
              type: ProtocolStepType.checkbox,
              order: 3,
            ),
            ProtocolStep(
              id: 'spirit_step_5',
              titleEn: 'Choose next action: walk / sleep / call someone.',
              titleTr: 'Sonraki adımı seç: yürüyüş / uyku / birini ara.',
              type: ProtocolStepType.checkbox,
              order: 4,
            ),
          ],
          recommendedFor: const ['lust', 'custom'],
        ),
        ProtocolTemplate(
          id: 'social_rescue',
          nameEn: 'Social Rescue (Break Isolation)',
          nameTr: 'Sosyal Kurtarma (Yalnızlığı Kır)',
          descriptionEn: 'Isolation fuels compulsion. Connection breaks it.',
          descriptionTr: 'İzolasyon kompulsiyonu besler. Bağ kurmak kırar.',
          steps: [
            ProtocolStep(
              id: 'social_step_1',
              titleEn: 'Step outside for 3 minutes.',
              titleTr: '3 dk dışarı çık.',
              type: ProtocolStepType.timer,
              durationSec: 180,
              critical: true,
              order: 0,
            ),
            ProtocolStep(
              id: 'social_step_2',
              titleEn: 'Send 1 message (template provided).',
              titleTr: '1 mesaj at (hazır şablon).',
              type: ProtocolStepType.action,
              critical: true,
              order: 1,
              detailsEn: '“Hey, I’m having a tough moment. Can we talk for 2 minutes?”',
              detailsTr: '“Kanka zor bir an yaşıyorum. 2 dk konuşabilir miyiz?”',
            ),
            ProtocolStep(
              id: 'social_step_3',
              titleEn: 'Do 10 minutes walk.',
              titleTr: '10 dk yürüyüş.',
              type: ProtocolStepType.timer,
              durationSec: 600,
              order: 2,
            ),
            ProtocolStep(
              id: 'social_step_4',
              titleEn: 'Return: start a safe activity.',
              titleTr: 'Geri dön: güvenli aktivite başlat.',
              type: ProtocolStepType.checkbox,
              order: 3,
            ),
          ],
          recommendedFor: const ['loneliness', 'lust', 'custom'],
        ),
      ];
}
